#version 460

layout(location=0)in vec3 inPosition;
layout(location=1)in vec3 inNormal;
layout(location=2)in vec2 inTexCoord;

layout(location=0)out vec3 outPosition;
layout(location=1)out vec3 outNormal;
layout(location=2)out vec2 outTexCoord;

layout(push_constant)uniform PushConstant{
    mat4 P,V,M;
}pc;

void main()
{
    outPosition=vec3(pc.M*vec4(inPosition,1.));
    outNormal=normalize(transpose(inverse(mat3(pc.M)))*inNormal);
    outTexCoord=inTexCoord;
}